### ISSUE TITLE
Add Support for the Other Samurai Shodowns

### ISSUE THREAD

**Issue by MasterO2** [peon2/fbneo-training-mode#1]
@peon2 

Please add support for:

Samsho
Samsho2
Samsho4
Samsho5
~~Samsh5sp~~ (Now Supported in https://github.com/peon2/fbneo-training-mode/commit/4ff8e46ca51529ffb160c7657672880924fbbb42)

**Comment by peon2** [comment]
Hey MasterO2 if I get chance to I will, but I'll definitely accept any pull requests that add support for those games!

**Comment by MasterO2** [comment]
> 
> 
> Hey MasterO2 if I get chance to I will, but I'll definitely accept any pull requests that add support for those games!

Thanks for clarifying.

**Comment by MasterO2** [comment]
@Bailey-Rudolph Any plans for **samsho2** as well?

**Comment by Bailey-Rudolph** [comment]
I eventually plan to add support for all the samsho games

**Comment by peon2** [comment]
Preliminary support for the other samsho games added with 9dd921c2
