### ISSUE TITLE
Lua run error xmvsf

### ISSUE THREAD

**Issue by VaGNaroK** [peon2/fbneo-training-mode#100]
fightcade 2 after the last update is no longer possible to play in training mode due to an error like the photo below, any solution since fightcade uses fbneo training mode?

[https://postimg.cc/mP8xdBxG](url)

[https://postimg.cc/zVHStk9D](url)

**Comment by Xcl4m4t10n** [comment]
It's working perfectly fine for me.

**Comment by peon2** [comment]
Are you using the latest version of the script? I can't replicate this

**Comment by VaGNaroK** [comment]
> Are you using the latest version of the script? I can't replicate this

training mode in fightcade 2 was not working after the update, so they fixed it in the recent update.
