### ISSUE TITLE
training mode hitboxes not turning off for me 

### ISSUE THREAD

**Issue by orlando8819** [peon2/fbneo-training-mode#104]
for some reason after fightcade update i cant turn off the hitboxes. i try every key but not working at all . i would like some help that i can get.

**Comment by yottsume** [comment]
I'm experiencing the same issue for ssf2xjr1. Would love to get a fix.

**Comment by peon2** [comment]
fightcade won't always use the latest version of this script, this was fixed with c73643b9
please test the latest version straight from my github instead of a potential older version from fightcade before opening an issue

**Comment by orlando8819** [comment]
> fightcade won't always use the latest version of this script, this was fixed with [c73643b](https://github.com/peon2/fbneo-training-mode/commit/c73643b9805337a6d1408d41cf1c46767858a90b) please test the latest version straight from my github instead of a potential older version from fightcade before opening an issue

thanks
