### ISSUE TITLE
Requesting Support for Fatal Fury Special, Fatal Fury 3, and the Real Bout Fatal Fury Series

### ISSUE THREAD

**Issue by MasterO2** [peon2/fbneo-training-mode#17]
@peon2 @Bailey-Rudolph or anyone else:

Game Name: Fatal Fury Special
Rom Name: **fatfursp**

Game Name: Fatal Fury 3 - Road to the Final Victory
Rom Name: **fatfury3**

Game Name: Real Bout Fatal Fury
Rom Name: **rbff1**

Game Name: Real Bout Fatal Fury 2 - The Newcomers
Rom Name: **rbff2**

Game Name: Real Bout Fatal Fury Special
Rom Name: **rbffspec**

**Comment by peon2** [comment]
Support added with 3292161

**Comment by MasterO2** [comment]
@peon2 I don't see Fatal Fury 3 in that commit, so was that just accidentally forgotten?

**Comment by peon2** [comment]
Forgot to add it to the commit, fatfury3 is now supported with 134971c
