### ISSUE TITLE
Issue with Fightcade 2.1.6 and garou rom

### ISSUE THREAD

**Issue by reylobo** [peon2/fbneo-training-mode#25]
I don't know if this issue prevails on other roms or if it is only a garou thing. But this started happening after the new updates from FC.
You try to run the lua script and this two error messages come up:

![image](https://user-images.githubusercontent.com/50371465/123662804-6bc88a80-d7fb-11eb-9d8b-1684c006e6c6.png)

**Comment by Bailey-Rudolph** [comment]
@reylobo hey so it looks like you are missing a dll file. You should be able to google that and find a download of it online. As for garou not working. There was a minor issue with the script that prevented it from working properly, it has now been fixed as of the latest pull request.
