### ISSUE TITLE
hi sorry not really a issue,  but a question 

### ISSUE THREAD

**Issue by xer05100** [peon2/fbneo-training-mode#34]
hope you someone can answer this. Is there way i can  save the inputs from a fightcade replay then play them back? i would like to replay certain situations that im having trouble in.

**Comment by Xcl4m4t10n** [comment]
You should ask this questions on fc git or discord. In any case the only way to do that is just watching the whole replay, you can't rip or record inputs at this moment. My recommendation: Record the video at 60fps with any screen recorder AND with input marks activated on FC2 then try to replicate it frame by frame with the frame-by-frame option on FBNeo.

**Comment by Xcl4m4t10n** [comment]
Now that I thinking more about this, I think that you can start the replay then start a re-recording by FBNeo and record only the interested part.

**Comment by xer05100** [comment]
Thanks for the reply, yeah ive asked in a few different discords and never got a reply or a solid answer. 

i thought it might be a thing, because the lua training mode script shows the inputs of both players when watch a replay. So i was hoping there was a lua script out there that could output player 1 and 2's inputs to a marcro. Wishful thing i guess.

**Comment by peon2** [comment]
I wrote two scripts in the past that could be adapted to work like that (https://github.com/peon2/Fightcade-Replay-Control) (https://github.com/peon2/fbneo-input-dump) but I never got around to getting that sort of functionality in particular to work.
