### ISSUE TITLE
Emulator freezes when selecting certain menu options.

### ISSUE THREAD

**Issue by Ausuri** [peon2/fbneo-training-mode#35]
When I open the menu I can select some options with no issues like hitboxes on/off, and scrolling inputs on/off. However, some menu options freeze the emulator and I have to kill the process. So far I've seen this when changing P1 meter refill options or replay slots. I've only tried these options on KoF97/98, but I'm guessing this happens with some other Neo-Geo games as well.

**Comment by Ausuri** [comment]
Just a sidenote, this happens with non-SNK games as well. I tried an older version (0.21.05.28) of the training mode and didn't have any crashes. It looks like there were some recent changes with the menu items, including the replay slots. Maybe these changes introduced some bugs? I tried glancing over the code but my lua skills aren't that great (non-existent, actually).

**Comment by Ausuri** [comment]
I noticed someone had a similar issue and pointed out that it doesn't crash on the latest release (0.21.08.06) which is correct. So I'm not sure if I need to close this ticket or not seeing as I'm pulling the source code as-is straight from the repository.

**Comment by peon2** [comment]
Shouldn't be crashing anymore in the latest release, mention it if it does.
