### ISSUE TITLE
Feature question/request: Block mode

### ISSUE THREAD

**Issue by Ausuri** [peon2/fbneo-training-mode#43]
Are there any plans to add random/always block modes, like the [Third Strike trainer](https://github.com/Grouflon/3rd_training_lua)? Seems like it may be difficult for a one-size-fits-all trainer, but just curious.

Edit: I mean for any games, not just for third strike of course.

**Comment by poliva** [comment]
I did this for SSF2X, take a look here: https://github.com/peon2/fbneo-training-mode/pull/68
