### ISSUE TITLE
Feature Request : Input Display Off

### ISSUE THREAD

**Issue by iwakiguile** [peon2/fbneo-training-mode#44]
As of right now, you can only change the size of input display, so it would be great if you could add a "Input Display off" option same as with the "Hitboxes off" option.

**Comment by Triple-067** [comment]
You can do that by going into the HUD settings, selecting either input display, and hiding them.

**Comment by iwakiguile** [comment]
Thanks for the reply, Triple-067. I took your advice and went to HUD settings, but it seems that the Hide (Middle Punch) function doesn't work. Other functions (select/weak punch and back/strong kick) work all right and I could move the HUD around and everything. Tested on the newest v.0.21.09.

I guess the this HUD malfunction is technically going to be a separate issue from the "Hide Input Display" feature request.

Anyways, I'm gonna keep the case opened for peon2 to see. I'll still appreciate the said feature even if the HUD issue was fixed.

**Comment by Triple-067** [comment]
Strange! It does work on neo geo games though, at least for me

**Comment by peon2** [comment]
@iwakiguile which game is it not working with? It's working properly from what I can see.

**Comment by iwakiguile** [comment]
@peon2 It's Super Turbo.

**Comment by iwakiguile** [comment]
It seems that the Medium Punch on my joystick was broken. I mapped the Medium Punch to keyboard, and indeed the "hide function" worked. Sorry to have troubled you guys!
