### ISSUE TITLE
Feature request: character select or save/load feature

### ISSUE THREAD

**Issue by Triple-067** [peon2/fbneo-training-mode#54]
I can't count the amount of times I wanted to switch characters and had to manually load my character select save state, often having to exit fullscreen. I think it would be great if there was a savestate for each game that could be loaded from the training menu that takes you right back to character select, with the option to replace the state with your own, and load it from the training menu at any point.

Even if you can't make savestates for every game, the option to make your own and place it in a folder would be a good option as well, or perhaps a built-in save feature that lets you create and load multiple saves for convenience. For example, I have multiple states for KoF '96, one of which sets the opponent to Kyo for me so I don't have to do anything on the 2p side, and another that allows me to select both characters freely.

If this gets added, a toggle to make a state load the moment the training mode script activates would be neat as well. As far as how I would implement it, I would create a menu tab for it that has its settings and 5 save states, and selecting a state will prompt you to either load/save/delete with load being the first option selectable, then add a 'quick load state 1' option in the basic settings for easy access. Or, perhaps put both 'load state 1' and 'save state options' in the basic settings.

**Comment by Triple-067** [comment]
> Why do you have to exit full screen? There are shortcuts to load specific states.

I think it only loads the current active state, which I often use in the middle of a training session with a specific character. I have custom savestates that I load manually with unlock bosses and show stun/guard crush values.

**Comment by Xcl4m4t10n** [comment]
You think wrong.

**Comment by Triple-067** [comment]
Are there hidden shortcuts? this is all I see
![Capture](https://user-images.githubusercontent.com/90721289/142282319-5135d6ee-f58b-43d2-8d31-b2b6a219a4ab.PNG)

**Comment by Xcl4m4t10n** [comment]
Those are the shortcuts, what more you want?

**Comment by Triple-067** [comment]
> Those are the shortcuts, what more you want?

Yes, technically you can use this feature, but it's incredibly frustrating to hold fn+f8/f11, load state, and switch back to the main slot I use while training, all while having no idea which slot you have selected, so I find it far more practical to just load the state manually every time.

**Comment by Xcl4m4t10n** [comment]
I don't think it's frustrating but in any case I'm not sure if you can do that kind of things with LUA. Did you try to ask for this to FC team? I think it would be a nice idea to have a shortcut to each savestate so maybe they can add it.

**Comment by Triple-067** [comment]
I think loading savestates is how the 3rd strike trials lua sets up it's various situations, so I think it's possible. However, that is a good suggestion for Fightcade and would basically fix this issue, though not gonna lie having it load on script startup and be accessible from the basic menu would still be really cool.

**Comment by peon2** [comment]
I've definitely considered adding some in-script support for the training mode and I have some cool ideas to implement. It's far down the pipeline at the minute as there's some more pertinent features to consider but one day we'll see :)
