### ISSUE TITLE
Vampire Savior support

### ISSUE THREAD

**Issue by DatGrey** [peon2/fbneo-training-mode#63]
Hi, first off let me thank everybody for working on the training script, it rocks. With that said, is someone planning on adding support for VSAV in the future?

**Comment by peon2** [comment]
VSAV is definitely on the cards, but nobody has gotten around to it due to an excellent dedicated training mode by @BornPosthumous already existing: https://github.com/BornPosthumous/VSAV_Training

**Comment by peon2** [comment]
I may add it anyone some day for the sake of completeness

**Comment by DatGrey** [comment]
Thanks for the reply, tbh yesterday after opening this issue I went ahead and tried my hand at it... I think I got a starting script working, now I just have to install git and understand how to add a pull request :P
