### ISSUE TITLE
SGEMF crashing whenever the script attempts to be loaded

### ISSUE THREAD

**Issue by Willytor** [peon2/fbneo-training-mode#65]
What it says on the title. It displays the known issues in the script window then the emulator closes.

**Comment by peon2** [comment]
It's probably not an issue with the script, at least not one I'm aware of.
Unfortunately fbneo can be a little unstable running larger scripts so crashes can happen, I've noticed that they seem to be more common with cps2 games but I can't be sure. If it's giving you a lot of trouble try reverting to an older version of the script that still supports sgemf.
