### ISSUE TITLE
Replay Editor freeze issue

### ISSUE THREAD

**Issue by iwakiguile** [peon2/fbneo-training-mode#71]
Whenever I finish editting replays via Replay Editor and exiting after, FBNeo freezes.
FBNeo starts working again in 5~10 seconds, but with the Replay Editor menu stuck on the forefront. 
Training mode refuses to respond (I can still move the characters and whatnot), and I can't do anything to get rid of the Replay Editor but to close FBNeo.
Tested on ssf2xjr1 (Super Turbo).

**Comment by peon2** [comment]
Fixed with 3554a2f
