### ISSUE TITLE
Guru Error

### ISSUE THREAD

**Issue by neontetra12** [peon2/fbneo-training-mode#79]
I'm not sure if what's causing this is an issue with my computer itself, but I have had no success in loading training mode. Browsing through error details, it seems it was unable to load a file.

Exception occurred in module fcadefbneo.exe:
          fcadefbneo.exe (base address 0x00980000, size 115608 KB)
          
         
         Initially, I asked the Art of Fighting discord for help on the issue, and was suggested to try the newer savestate (https://discord.com/channels/360482529091780615/729427069876043818/957728418378711210), but still had no success. I am also operating Windows 11 and Fightcade v2.1.26. Would you by any chance know if this is an error on my end or with the training mode? The help would be very much so appreciated.

**Comment by MasterO2** [comment]
@peon2 Can you assist on this issue regarding **Art of Fighting 2**?  Thanks.

**Comment by peon2** [comment]
Hi @neontetra12, I'm not sure what the problem is. Occasionally fbneo (especially fc branch) will crash when launching the training mode, but it tends to usually work for me. I don't know why you would be consistently crashing.

**Comment by peon2** [comment]
Disabling scrolling inputs introduced with 96f77c82 which should stop this crashing
