### ISSUE TITLE
Feature Request for the Neo Geo Samsho Games: Infinite Rage Meter Option

### ISSUE THREAD

**Issue by MasterO2** [peon2/fbneo-training-mode#80]
@peon2 I am requesting an **Infinite Rage Meter** option for the Neo Geo Samsho games.   

(Samsho 1 and 2 call it a POW Meter, iirc).

**Comment by peon2** [comment]
Hi @MasterO2, infinite rage meter should already be implemented under meter. Can you give me an example where it's not working?

**Comment by MasterO2** [comment]
@peon2 Unless I'm going crazy, I'm not seeing a Rage Meter option anywhere:

 https://postimg.cc/mPXS2p2s

**Comment by peon2** [comment]
You might need to restart the script after choosing your characters.

**Comment by MasterO2** [comment]
> You might need to restart the script after choosing your characters.

@peon2 

I started the script at the Neo Geo screen, then selected my characters and went into the fight itself.  

Based on your advice, **after** the fight started, I restarted the script. 

The P1 and P2 lifebars then worked properly, but strangely, only P2's **rage meter** was filled.  

*When I had P2 hit P1, it was only then that P1's rage meter filled up*.  I'm not sure if that's a bug in the script or not, but if it is, I imagine that's easily fixable.

**Comment by peon2** [comment]
I think in some of the games there are visual glitches associated. Try doing a super special move and seeing what happens? Which game is it specifically you're having trouble with?

**Comment by MasterO2** [comment]
> I think in some of the games there are visual glitches associated. Try doing a super special move and seeing what happens? Which game is it specifically you're having trouble with?


The issue I described with the P1 Rage Meter was in **Samsho2**.

**Comment by Ausuri** [comment]
If I remember correctly, there was a visual glitch in Samsho2 when the script starts. It doesn't show the meter as full initially but you can still use a super.

**Comment by MasterO2** [comment]
I can confirm what Ausuri said above, @peon2 , so I'm closing this issue.  Fixing that visual glitch shouldn't be difficult for you or anyone else.
