### ISSUE TITLE
tableio's table.load() crashes the emulator in some games

### ISSUE THREAD

**Issue by poliva** [peon2/fbneo-training-mode#86]
Not sure if it's an issue specific to my computer, but when I try to start some games, if the games/<game>/config.lua does not exists, the training mode starts successfully with the default values, however if the config.lua does exist, the emulator crashes.

Steps to replicate:
- Make sure games/sfa3/config.lua does not exist.
- Start sfa3 training mode, the default config.lua will be created. Close sfa3.
- Start sfa3 again. Emulator will crash.

Replacing table.load() to just return "nil" avoids the crash, so i'm guessing the issue is something there, but haven't been able to figure out what.

**Comment by peon2** [comment]
Crashes seem to most commonly occur with file reads and gd image building/reading. I've tried to make it a little more consistent with 34691e74 but I wonder if there's an underlying issue with the gd library or interfacing with it.

**Comment by poliva** [comment]
The issue seems to be only with games that use `cps2-hitboxes`

**Comment by poliva** [comment]
This seems to fix it in the games i have tried, and doesn't seem to break anything else:
https://github.com/poliva/fbneo-training-mode/commit/3db35db4a7403f9e1b1d1c6307e881b7882b42fc

it probably needs more testing before it's ready to ship.

**Comment by poliva** [comment]
ok, i've done some more extensive testing and it seems to do the trick. CPS2 hitboxes are displayed correctly, and the emu doesn't crash anymore. I'm going to submit a pull req with it.
