### ISSUE TITLE
Crash when saving a replay in slot 1 and 3 but not in slot 2

### ISSUE THREAD

**Issue by zass30** [peon2/fbneo-training-mode#93]
Go into replay editor. Create commands in save slot 1, and then save slot 3. Then go back to replay editor. Script will crash with this error: 

![image](https://user-images.githubusercontent.com/2244451/184989790-c507af5b-4972-4832-9a6f-770d9212e4ca.png)

**Comment by peon2** [comment]
Fixed with 96f77c82
