### ISSUE TITLE
Breakers Revenge Extra

### ISSUE THREAD

**Issue by Xcl4m4t10n** [peon2/fbneo-training-mode#95]
I just cloned "breakrev" folder inside "games", then rename it to "brkrevext". Same with "breakrev.lua", renaming it as "brkrevext.lua". Finally, in "fbneo-training-mode.lua", I added "brkrevext = {"brkrevext", iconfile = "icons-neogeo-32.png"}," in line 30. 

It's working like it should on "breakrev" as they are virtually the same game, could you please add it "officially"? Thank you!

**Comment by peon2** [comment]
Added with v0.22.09
